### ISSUE TITLE
Method proxyChain.anonymizeProxy(oldProxyUrl) fails cause cannot pick the port

### ISSUE THREAD

**Issue by maZahaca** [apifytech/proxy-chain#10]
OS: MacOS
Version: 0.1.26
Problem: Method proxyChain.anonymizeProxy(oldProxyUrl) fails cause cannot pick the port.
It happens over and over again:
```
  portastic:find Result reached the maximum of 1 ports, returning... +0ms
  portastic:test Trying to test port 39565 +0ms
  portastic:test TCP server on port 39565 closed +0ms
  portastic:test Port 39565 was free +0ms
  portastic:find Result reached the maximum of 1 ports, returning... +0ms
  portastic:test Trying to test port 39566 +0ms
  portastic:test TCP server on port 39566 closed +1ms
  portastic:test Port 39566 was free +0ms
  portastic:find Result reached the maximum of 1 ports, returning... +0ms
```

Do you have any guesses of the roots of this problem?

**Comment by maZahaca** [comment]
Hello, any comments there?

**Comment by gippy** [comment]
Hi, 

I have been playing around with this and it looks like something is closing the testing service running on selected ports (my idea is your firewall). Looking at the [portastic codebase ](https://github.com/alanhoff/node-portastic/blob/master/lib/portastic.js) it opens a tcp node server but the server is then closed and therefore portastic attempts to use other port. Could you try to test just portastic on your machine (cli should be fine)? Just to make sure that we isolate the source of the issue.

Let me know if you have any news.

**Comment by jancurn** [comment]
Closing this until we have more information,

**Comment by Nicklason** [comment]
I have had a similar issue and made a pull request to portastic that fixes it: https://github.com/alanhoff/node-portastic/pull/13
