### ISSUE TITLE
Multiple ports with alternate upstream proxies

### ISSUE THREAD

**Issue by necevil** [apifytech/proxy-chain#19]
Hey guys great project.
I am looking at either running multiple instances of proxy-chain or alternately finding a way to listen on multiple ports (but specify different upstream proxy based on the port a request lands on).

My question is:
Which do you think makes more sense?

I didn't see anything in the docs about setting a single instance to listen on more than one port so I guess if that isn't a possibility then I will fall back and spin multiple instances which may make more sense anyway?

**Comment by jancurn** [comment]
Hi there, currently the proxy server can only listen on a single port. If you need to listen on multiple ports, I'd recommend launching multiple instances.

**Comment by jancurn** [comment]
I'm closing this issue for now, feel free to reopen.

**Comment by necevil** [comment]
Thanks Jan! Will do.
Closed is fine!
