### ISSUE TITLE
Periodic ERR_TUNNEL_CONNECTION_FAILED in Chrome

### ISSUE THREAD

**Issue by mhluska** [apifytech/proxy-chain#23]
I'm using this with Capybara / Selenium WebDriver and notice sporadic `ERR_TUNNEL_CONNECTION_FAILED` errors when trying to load a page. Refreshing doesn't help. Some attempts work, some don't. I don't see any other error messages so I'm not really sure how to debug this. The only variable that changes between attempts is the upstream proxy hostname.

Versions:

chromedriver: `ChromeDriver 2.36.540469 (1881fd7f8641508feb5166b7cae561d87723cfa8)`
chrome: `Version 68.0.3440.106 (Official Build) (64-bit)`
capybara: `3.6.0`
capybara-webkit: `1.15.0`
proxy-chain: `0.2.4`

Running the `ps` command, here's how the process looks that Capybara spawns:

```
/Applications/Google Chrome.app/Contents/MacOS/Google Chrome --disable-background-networking --disable-client-side-phishing-detection --disable-default-apps --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --disable-web-resources --enable-automation --enable-logging --force-fieldtrials=SiteIsolationExtensions/Control --ignore-certificate-errors --load-extension=/var/folders/kl/y1jrp7zs55sbx075jjjl3p280000gn/T/.org.chromium.Chromium.PogJ9o/internal --log-level=0 --metrics-recording-only --no-first-run --password-store=basic --proxy-server=http://127.0.0.1:34700 --remote-debugging-port=12736 --test-type=webdriver --use-mock-keychain --user-data-dir=/var/folders/kl/y1jrp7zs55sbx075jjjl3p280000gn/T/.org.chromium.Chromium.XKkbMD --window-size=1440,900 data:,
```

**Comment by mhluska** [comment]
I tried removing most of the command-line arguments and executing manually but the issue persists. I'm leaning towards this being an issue with the VPN provider. I'm going to close for now.

**Comment by babyrusa** [comment]
Same issue

**Comment by fuergaosi233** [comment]
Same issue
