### ISSUE TITLE
https request identification

### ISSUE THREAD

**Issue by elpaxel** [apifytech/proxy-chain#36]
When I am sending request to HTTPS page through proxy-chain with prepareRequestFunction there is no useful info about request for identification.  
For example if I am opening one HTTPS website two times in a row I want it to be passed through different proxies. But next time when I will open this website two times I need it to use the same proxies.

**Comment by jancurn** [comment]
Actually, there is no such thing as HTTPS proxy. HTTPS traffic goes over a normal HTTP proxy using the HTTP CONNECT tunnel. Have you tried using `http://username:password@proxy.example.com:3128` ?

**Comment by elpaxel** [comment]
Thanks for your answer, but I'm solve my previous problem with [https://github.com/sjitech/proxy-login-automator](url). I've edited my question.

**Comment by jancurn** [comment]
The only parameters you can see in the `prepareRequestFunction` are: proxy username and password, hostname, port. For example, [Apify Proxy](https://apify.com/docs/proxy) uses username to pass configuration settings.

Potentially we could also process headers passed to `HTTP CONNECT` request, but AFAIK there is no easy way to pass these headers from Chrome.

**Comment by jancurn** [comment]
I'm closing this issue for now, please reopen it if needed.
