### ISSUE TITLE
Break connection with custom status code

### ISSUE THREAD

**Issue by IvanMMM** [apifytech/proxy-chain#49]
Hello.
I have an issue with breaking connection, that I don't want to continue. Let's say, I want to use proxy-chain as a load-balancer for my other proxies. But I want to select node depending on username and password. If password is incorrect or i have no addresses/nodes available - I want to reject this connection and set custom error status. For now I can only throw new Error(...) from customResponseFunction to break this connection. Can I do it more graceful, with setting statusCode and message? Thank you.

**Comment by jancurn** [comment]
Hi there, you can use the `RequestError` class for this, I've just added info about it to README. See https://github.com/apifytech/proxy-chain/commit/86b8f030b78ed71e21e8de27fdf1a68e4d9a2451
