### ISSUE TITLE
Error at TCP.onStreamRead (internal/stream_base_commons.js:111:27)

### ISSUE THREAD

**Issue by scottk** [apifytech/proxy-chain#51]
Hi,

I'm consistently getting this error sometime after "target socket assigned" and I have no idea why the error handling isn't catching it. This is via CONNECT through the handler base/handler chain workflow

**Comment by scottk** [comment]
I found the issue, there's a socket in prepareRequestHandling that isn't properly error handled in a very tiny gap of time.

**Comment by jancurn** [comment]
Great that you were able to fix it!
