### ISSUE TITLE
Is it possible to analyze the HTTPS traffic?

### ISSUE THREAD

**Issue by melalj** [apifytech/proxy-chain#52]
It seems that proxy-chain is using HTTP CONNECT for https addresses. I'm looking for a way to bypass the proxy for static assets (img, js, css, font). Since most of the websites are under an SSL certificate, not sure if it's possible to do so.
I saw that https://github.com/luminati-io/luminati-proxy is able to do it but limited to its own proxy.
Any idea?

**Comment by jancurn** [comment]
Well, I think the only way to inspect HTTPS traffic is by using a self-signed certificate, forcing the client to use it and then encrypt the traffic on the proxy using the certificate (a man-in-the-middle "attack"). See https://blog.apify.com/using-a-man-in-the-middle-proxy-to-scrape-data-from-a-mobile-app-api-e954915f979d

**Comment by jancurn** [comment]
Closing this, feel free to reopen if needed.
