### ISSUE TITLE
Can you elaborate on the statistics method?

### ISSUE THREAD

**Issue by brdeav39** [apifytech/proxy-chain#54]
Hi,

Can you elaborate at all on what these numbers represent:

```
{
    srcTxBytes: Number,
    srcRxBytes: Number,
    trgTxBytes: Number,
    trgRxBytes: Number,
}
```

For example, I tried doing a test with postman by doing a GET request to the README of your repository, but the size of request and response did not match up with any combination of the metrics above. Please help! This is a great tool but I'm having trouble measuring the traffic.

Thanks.

**Comment by jancurn** [comment]
I updated the README at https://github.com/apifytech/proxy-chain with more detailed info.

**Comment by jancurn** [comment]
I forgot to mention - the fact the size of request and response doesn't match can be caused by additional data passed on the raw sockets, e.g. HTTP headers, SSL protocol stuff and so on.
