### ISSUE TITLE
username and password are null - but are being sent

### ISSUE THREAD

**Issue by brdeav39** [apifytech/proxy-chain#55]
ive noticed with some of the tools I use, basic authentication does not work - the username and password are null in the prepareRequestFunction. I think they must be getting lost somehow in the CONNECT event - any idea what might be causing this?

**Comment by jancurn** [comment]
Are you using `Authorization` or `Proxy-Authorization` HTTP header? Only the latter one works for the proxy

**Comment by brdeav39** [comment]
AH - I think I just figured it out after some trial/error. It seems I was only sending the Proxy-Authorization header upon receiving the 407 code. So I was able to check if user/pass are null, and return an object with requestAuthentication: true. this triggers my program/tool to then send the proper header.

**Comment by jancurn** [comment]
Cool, closing this for now.
