### ISSUE TITLE
Override the request before routing it to the upstream proxy

### ISSUE THREAD

**Issue by SandratraRM** [apifytech/proxy-chain#56]
I send a request to the proxy chain server with some specific header that i don't want to send to the upstream proxy. 

I use that header to generate the upstream url in the prepareRequestFunction so i dont need to restart the server to change proxy and i already know how to fetch it but i want to remove it once i have generated the upstream url so it wont be send to the upstream proxy.

I have tried something like this but the header is still sent:
```js
...
prepareRequestFunction: ({
      request,
      username,
      password,
      hostname,
      port,
      isHttp,
    }) => {
        let upstreamProxyUrl;
        if (request.headers['proxy-to-use'] === undefined) throw new ProxyChain.RequestError("No proxy-to-use request header",400);
        upstreamProxyUrl = `http://${_username}:${_password}@${request.headers['proxy-to-use']}`;
        delete request.headers['proxy-to-use'];
        return {
          upstreamProxyUrl 
        };
    }
...
```

How can i change some property of the request object before sending the request to the upstream proxy?

**Comment by jancurn** [comment]
I assume you're using HTTP, not HTTPS, correct?

The `proxy-chain` package copies the headers from the `request.rawHeaders` field, so you'd have to update that one as well.

**Comment by jancurn** [comment]
Closing this now, feel free to reopen the issue if using `request.rawHeaders` doesn't solve the issue.
