### ISSUE TITLE
Cannot receive RequestError on client using https request

### ISSUE THREAD

**Issue by theArina** [apifytech/proxy-chain#58]
What I'm trying to do is:
`           throw new ProxyChain.RequestError('Only Bob can use this proxy!', 400);     
`
So when I use http, works fine, I receive an error I sent, but when I use https, I get -111 TUNNEL_CONNECTION_FAILED.

I kinda get why it might happen, but what do I do if I want receive my error, instead of -111?

**Comment by jancurn** [comment]
Sorry but that's not possible, you can't inject any content into a HTTPS (TLS/SSL) tunnel. That only works in HTTP. Well, unless you force the clients to use your own self-signed certificate and somehow intercept and rewrite the HTTPS responses.... but that might be quite tricky.

**Comment by jancurn** [comment]
Closing this for now.

**Comment by theArina** [comment]
@jancurn okay, got it. Thanks for the reply
