### ISSUE TITLE
Proxy can easily be detected

### ISSUE THREAD

**Issue by NikolaiT** [apifytech/proxy-chain#59]
Hi,

First of all, awesome work. I really like the idea of this project. 

After inspection I saw that a couple of hop-by-hop headers such as 

```js
const HOP_BY_HOP_HEADERS = [
    'Connection',
    'Keep-Alive',
    'Proxy-Authenticate',
    'Proxy-Authorization',
    'TE',
    'Trailers',
    'Transfer-Encoding',
    'Upgrade',
];
```
are stripped from the forwarded http request that is passed to the upstream proxy.

This essentially means that there is no way to establish a Web Socket Connection when using this proxy. Web Sockets are initiated with the `Connection` and `Upgrade` header. When those headers are stripped, a targeted website could simply block the crawling/scraping based on the fact that the client is unable to establish a WebSocket connection.

This is just an example. The proxy could be detected via many other ways. 

Wouldn't it be possible to use an transparent proxy on TCP/IP level (socks) that forwards the packet stream?

I am aware that this would mean that http/s proxies cannot be used anymore, but at least it would eliminate the detection methods...

Any ideas?

**Comment by jancurn** [comment]
The web socket connections should work fine over HTTP mode, have you tried that?

BTW, for HTTPS, the proxying is made via so-called `HTTP CONNECT` tunnel, in which the proxy doesn't change any HTTP headers and content at all. So, for HTTPS, the proxy is practically undetectable. You can use this sort of proxying even for HTTP traffic, in fact for any TCP protocol, e.g. FTP. Just make sure your client connects using `HTTP CONNECT` method.

**Comment by jancurn** [comment]
Closing this for now, feel free to reopen if needed.
