### ISSUE TITLE
How to update upstreamProxyUrl dynamically ? 

### ISSUE THREAD

**Issue by lobstrio** [apifytech/proxy-chain#61]
I would like to use proxy-chain with multiple upstreamProxyUrl. Does someone would advise on the best way to dynamically update upstreamProxyUrl ? 

Thanks
Simon

**Comment by jancurn** [comment]
In `prepareRequestFunction` you have to pick one upstream proxy URL. If you have more, just pick one randomly. Or how else would you like this to behave and for what use case?

**Comment by lobstrio** [comment]
I would like to change the upstream proxy URL over time, to change the proxy I will connect to. Is that something you would thing possible ?

**Comment by jancurn** [comment]
It's not possible to switch connection on-the-fly, that would break it. You can cancel the connection yourself, the client will try to reconnect and at that moment you can give them another upstream proxy URL.

**Comment by jancurn** [comment]
Since this is not an issue to be fixed, I'm closing this for now.
